name: sepsis_env
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==1.11.0
      - numpy==1.21.5
      - pandas==1.2.5
      - tqdm==4.61.1
      - matplotlib
      - seaborn==0.11.2
      - sci-kit-learn==1.0.2
      - imblearn==0.0